name: Jest & React Testing Library
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API: https://e-commerce-paps.herokuapp.com
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
